namespace: seccomp-diff
# nodename: shmoocon-cluster-v129cillium-controlplane

image:
  repository: antitree/seccomp-diff
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

## Custom profiles supported by default:
# profile-block-all.json (Warning!! will likely not let you start a container)
# profile-complain-unsafe.json
# profile-allow-unsafe.json
# profile-complain-block-high-risk.json
# profile-runc-default.json
# profile-hello-shmoo.json
# unconfined - none applied at all
# RuntimeDefault - uses base runtime config

demos:
  enabled: true
  deployments:
  - name: happyshmoocon-default
    image: antitree/happyshmoocon:latest
    type: RuntimeDefault
  - name: happyshmoocon-custom
    image: antitree/happyshmoocon:latest
    seccompProfile: "profile-happy-shmoocon.json"
  - name: demo4
    image: nginx:latest
    seccompProfile: "profile-complain-unsafe.json"
  - name: demo6
    image: nginx:latest
    type: RuntimeDefault