namespace: seccomp-diff
# nodename: seccompdiff-cluster-v129cillium-controlplane

image:
  repository: antitree/seccomp-diff
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

agent:
  enabled: true
  port: 8000
  containerdSocket: /run/containerd/containerd.sock

## Custom profiles supported by default:
# profile-block-all.json (Warning!! will likely not let you start a container)
# profile-complain-unsafe.json
# profile-allow-unsafe.json
# profile-complain-block-high-risk.json
# profile-runc-default.json
# profile-hello-shmoo.json
# unconfined - none applied at all
# RuntimeDefault - uses base runtime config

demos:
  enabled: true
  deployments:
  - name: happyseccompdiff-default
    image: antitree/happyseccompdiff:latest
    type: RuntimeDefault
  - name: happyseccompdiff-custom
    image: antitree/happyseccompdiff:latest
    seccompProfile: "profile-happy-seccompdiff.json"
  - name: demo4
    image: nginx:latest
    seccompProfile: "profile-complain-unsafe.json"
  - name: demo6
    image: nginx:latest
    type: RuntimeDefault
