apiVersion: v1
kind: Service
metadata:
  name: seccomp-diff-agent
  namespace: {{ .Values.namespace | default "seccomp-diff" }}
  labels:
    app: seccomp-diff-agent
spec:
  clusterIP: None
  selector:
    app: seccomp-diff-agent
  ports:
  - name: http
    port: 8000
    targetPort: 8000
