apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seccomp-diff-agent
  namespace: {{ .Values.namespace }}
  labels:
    app: seccomp-diff-agent
spec:
  selector:
    matchLabels:
      app: seccomp-diff-agent
  template:
    metadata:
      labels:
        app: seccomp-diff-agent
    spec:
      hostPID: true
      containers:
      - name: agent
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["python", "-m", "agent.agent"]
        ports:
        - name: http
          containerPort: 8000
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_PTRACE
        volumeMounts:
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        - name: containerd-socket
          mountPath: {{ .Values.agent.containerdSocket }}
        env:
        - name: CONTAINERD_SOCKET
          value: {{ .Values.agent.containerdSocket | quote }}
      volumes:
      - name: host-proc
        hostPath:
          path: /proc
      - name: containerd-socket
        hostPath:
          path: {{ .Values.agent.containerdSocket }}
