{{- if .Values.demos.enabled }}
{{- range .Values.demos.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .name }}
    labels:
      app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        {{- if .command }}
        command: {{ .command }}
        {{- end }}
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          seccompProfile:
            {{- if .type }}
            type: {{ .type }}
            {{- else }}
            type: Localhost
            localhostProfile: operator/{{ $.Values.namespace }}/{{ .seccompProfile }}
            {{- end }}
{{- end }}
{{- end }}