apiVersion: apps/v1
kind: Deployment
metadata:
  name: seccomp-diff
  namespace: {{ .Values.namespace | default "seccomp-diff" }}  # Dynamically set the namespace
  labels:
    app: seccomp-diff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seccomp-diff
  template:
    metadata:
      labels:
        app: seccomp-diff
    spec:
      {{- if .Values.nodename }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - {{ .Values.nodename }}
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
      - name: seccomp-diff
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AGENT_ENDPOINTS
          value: "http://seccomp-diff-agent.{{ .Values.namespace | default "seccomp-diff" }}.svc.cluster.local:{{ .Values.agent.port }}"
        command: ["flask"]
        args: ["run", "--debug"]
