apiVersion: v1
kind: Service
metadata:
    name: seccomp-diff
    namespace: {{ .Values.namespace | default "seccomp-diff" }}
    labels:
        app: seccomp-diff

spec:
    type: {{ .Values.service.type }}
    ports:
      - port: {{ .Values.service.port }}
        targetPort: 5000
        protocol: TCP
        name: http
        {{- if eq .Values.service.type "NodePort" }}
        nodePort: {{ .Values.service.nodePort }}
        {{- end }}
    selector:
        app: seccomp-diff
