name: Semgrep

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "**" ]  # All branches

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Needed for PR comments

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto  # or use p/ci or a custom ruleset
